"""Chemical identity of a structure, separated from its conformation.

The reaction network is a graph over chemical macrostates; conformers of one
macrostate live inside it. That split only works if chemical identity is computed in a
way that is blind to conformation and blind to atom labelling:

Blind to conformation. A signed torsion about a rotatable single bond distinguishes
gauche+ from gauche-, which are the same substance. Including it would split one
macrostate in two and reproduce the combinatorial explosion the hierarchy exists to
prevent. Only configurational stereochemistry -- parity that cannot change without
breaking a bond -- belongs in the key: tetrahedral parity at genuine stereocentres and
E/Z parity across bonds that are both short enough to be multiple and are bridges
rather than ring members.

Blind to atom labelling. Under the fixed atom mapping of this MVP, transferring any
one of three equivalent methyl hydrogens yields a different set of atom indices for
the same reaction. Keying on raw edge sets would record three products where there is
one, so the graph part of the key is a colour-refinement hash that is invariant under
graph automorphism. Refinement is invariant by construction but not a provably
complete canonical form; for molecular graphs at these sizes it separates every case
encountered, and a collision would merge two chemistries rather than invent one.

Charge and spin enter the key only when the potential actually responds to them.
MACE-OFF returns identical energies for total charge 0, -1 and +1, so declaring
charge_sensitive keeps charged chemistry out of the search space instead of letting it
in unnoticed.
"""

import hashlib
import json
import numpy as np
from ase.data import chemical_symbols
from .canonical import canonical_form, refine
from .state import encode, resolve_active

# Prose that ships inside the records this module writes. Held as named constants
# rather than inline in the dict literals so the shape of each record is visible at
# a glance; the text is part of the output contract, so changing one is a schema
# change and not a comment edit.
_REACTION_EVENT_KEY_MEANING = (
    "reaction-event identity: canonical under the group generated by the endpoints' "
    "automorphisms, and undirected. NOT "
    "a chemical-state identity"
)


def _digest(text):
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def canonical_labels(numbers, edges, index):
    """Automorphism-invariant colour per atom; equal colours mean equivalent atoms.

    Thin wrapper over `refine` (prrs.canonical) since PLAN_2026-09-20.md section 1.1:
    without edge colours the two are byte-identical, stop rule and signature included.
    The colour-consuming paths here and in network.py / perturbations.py keep calling
    this exactly as before; the IDENTITY path no longer stops at colours -- colours are
    a refinement's output, not a certified orbit -- which is what `canonical_form` and
    the group/orbits it certifies are for.
    """
    return refine(numbers, edges, index)


def _bridges(edges, index):
    """Bonds whose removal disconnects the graph, so ring bonds are excluded."""
    adjacency = {int(i): [] for i in index}
    for a, b in edges:
        adjacency[a].append(b)
        adjacency[b].append(a)
    discovery, low, found, clock = {}, {}, set(), [0]

    def walk(node, parent):
        discovery[node] = low[node] = clock[0]
        clock[0] += 1
        for neighbour in adjacency[node]:
            if neighbour == parent:
                continue
            if neighbour not in discovery:
                walk(neighbour, node)
                low[node] = min(low[node], low[neighbour])
                if low[neighbour] > discovery[node]:
                    found.add((min(node, neighbour), max(node, neighbour)))
            else:
                low[node] = min(low[node], discovery[neighbour])

    for atom in adjacency:
        if atom not in discovery:
            walk(atom, None)
    return found


def _fragments(edges, index):
    parent = {int(i): int(i) for i in index}

    def root(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    for a, b in edges:
        parent[root(a)] = root(b)
    groups = {}
    for atom in parent:
        groups.setdefault(root(atom), []).append(atom)
    return list(groups.values())


def _formula(numbers, atoms_in_fragment):
    from ase import Atoms

    return Atoms(
        numbers=[int(numbers[i]) for i in sorted(atoms_in_fragment)]
    ).get_chemical_formula()


def _stabiliser_orbits(neighbours, group, slot, atom):
    """Partition `neighbours` into orbits under the subgroup fixing `atom` (P1-3).

    A colour tie is a GUESS that the tied neighbours are equivalent; the certified
    answer is whether some automorphism fixing the centre actually swaps them.
    """
    stab = [g for g in group if int(g[slot[atom]]) == atom]
    remaining, orbits = list(neighbours), []
    while remaining:
        seed = remaining.pop(0)
        orbit, frontier = {seed}, [seed]
        while frontier:
            current = frontier.pop()
            for g in stab:
                image = int(g[slot[current]])
                if image not in orbit and image in remaining:
                    orbit.add(image)
                    remaining.remove(image)
                    frontier.append(image)
        orbits.append(sorted(orbit))
    return orbits


def _tetrahedral_parities(
    positions, numbers, edges, index, labels, tolerance, group=None, canonical=None
):
    """Parity at atoms with four neighbours that are all inequivalent.

    Four distinct colours is SUFFICIENT for a real stereocentre (colour equality is
    necessary for equivalence, so distinct colours certify distinct orbits), and that
    is the whole criterion when no certified group is available. It is not NECESSARY:
    two neighbours can share a colour while no automorphism fixes the centre and swaps
    them -- a true stereocentre the colour rule silently skipped (P1-3). With a
    certified `group` (and `canonical`, the canonical order it came with), the
    criterion is four distinct orbits under Stab(centre), and ties inside one orbit
    are broken by canonical position rather than left to enumeration luck.

    Measured on the recorded corpus (2136 frames, docs/experiments/orbit_vs_colour_
    probe.py, 2026-09-20): colour and orbit criteria agree on every frame, so this
    change is free there -- it tightens identity only on structures the corpus has
    not yet produced.

    Notes
    -----
    [1] Dividing by the three edge lengths leaves the sign untouched and makes the magnitude
        a shape, not a size: it is a signed volume ratio in [-1, 1] that does not move when
        the molecule is scaled or when a different element sits at the centre. Without it
        there is no threshold that can serve both a C-C skeleton and a C-H one, so
        `int(np.sign(...))` was reading the sign of a number whose scale was unknown -- and
        at a near-planar centre that number is float noise, so thermal jiggle alone flips
        the recorded configuration and mints a new macrostate. np.sign(0.0) is 0 as well,
        which silently became a third parity value that no chemistry corresponds to.
    """
    order = [int(a) for a in index]
    slot = {atom: k for k, atom in enumerate(order)}
    adjacency = {int(i): [] for i in index}
    for a, b in edges:
        adjacency[a].append(b)
        adjacency[b].append(a)
    parities = []
    for atom, neighbours in adjacency.items():
        if len(neighbours) != 4:
            continue
        colours = [labels[n] for n in neighbours]
        if len(set(colours)) != 4:
            if group is None:
                continue
            orbits = _stabiliser_orbits(list(neighbours), group, slot, int(atom))
            if len(orbits) != 4:
                continue
        rank = canonical if canonical is not None else {n: n for n in index}
        ordered = [
            n for _, n in sorted(zip(colours, neighbours), key=lambda cn: (cn[0], rank[cn[1]]))
        ]
        base = positions[ordered[0]]
        edges_from_base = np.array(
            [
                positions[ordered[1]] - base,
                positions[ordered[2]] - base,
                positions[ordered[3]] - base,
            ]
        )
        volume = float(np.linalg.det(edges_from_base))
        # [1] dividing by the edge lengths makes it a shape
        lengths = np.linalg.norm(edges_from_base, axis=1)
        scale = float(np.prod(lengths))
        shape = volume / scale if scale > 1e-30 else 0.0
        # A real sp3 centre is nowhere near this: the ratio for an ideal tetrahedron is
        # order 0.1, and a planar one is exactly zero. Below the band the configuration is
        # reported as absent rather than guessed, because a token that stays put is worth
        # more here than a sign that is right half the time.
        parities.append(
            [labels[atom], int(np.sign(shape)) if abs(shape) > tolerance else "planar"]
        )
    return sorted(parities, key=lambda entry: (entry[0], str(entry[1])))


# Neutral closed-shell valences. Deliberately small: the first version has to be right on
# C/H/O, which covers every benchmark, plus the monovalent halogens, which are terminal and
# unambiguous in neutral organic molecules. Nitrogen, phosphorus and sulfur are left out on
# purpose -- their valences are not single-valued in that setting -- and anything outside
# this table is reported unresolved rather than guessed at.
VALENCE = {1: 1, 6: 4, 8: 2, 9: 1, 17: 1, 35: 1, 53: 1}


# The shared convention this key encodes, stated so it can be argued with.
#
# Model-independent by construction: nothing here reads an energy, a force or a barrier.
# Same structure, same charge and spin, same protocol -> same key, whichever calculator is
# attached. That is a property of the DEFINITION, and it is not the same claim as "different
# models give the same identity": different models optimise to different structures, and
# those may legitimately be different substances. P3's three models agreeing on (A, B) is an
# OBSERVATION worth having, not a requirement written into the definition -- writing it in
# would hide the case where a model really does predict a different product.
#
# Rotational barriers and what can actually interconvert are measured on a potential energy
# surface, at a temperature, under a tolerance. They belong to the dynamics layer --
# `free_bonds_of` and the microstate matcher already use them there, tagged with the model
# that produced them. They must not silently rewrite the shared identity.
#
# Scope of the current resolver: neutral closed-shell integer valences over
# H, C, O, F, Cl, Br, I. Outside that it returns unknown, and unknown is recorded as
# unknown -- not as "no stereochemical difference", and not as grounds to refuse a species.
_CONFIGURATION_PROTOCOL = "lewis-neutral-closed-shell/2026-09-04"


# Reasons that mean "the budget ran out", as opposed to "this molecule cannot be
# resolved". The distinction is the whole point of IdentityUnavailable below.
BUDGET_REASONS = frozenset({"enumeration_limit", "candidate_limit"})


class IdentityUnavailable(RuntimeError):
    """The identity could not be computed inside the enumeration budget.

    Not the same thing as "this substance's stereochemistry cannot be resolved". That is a
    property of the molecule -- an element outside the valence table, a graph no neutral
    closed-shell assignment satisfies -- and it is recorded in the key as
    `stereo_unresolved`, so a resolved substance is never compared against an unresolved
    one on the quiet.

    A budget overflow is a property of the RUN. Measured on the P3 A structure:

        bond_order_limit = 1000  ->  key 8710064d12ce6a5a
        bond_order_limit =  100  ->  key 38584b6ee5c4eca2

    Same molecule, same geometry, same code. Returning a key at all in that state makes
    chemical identity a function of how much compute the enumerator was allowed, which is
    not a chemical statement about anything. The event key has the same defect in a
    quieter form: when `automorphisms` gives up it returns the identity permutation alone,
    so the bond delta is canonicalised against an incomplete group and the key moves
    without any field saying so.

    So this raises rather than returning a degraded answer -- HANDOFF.md section 2:
    "fail closed. If it cannot be decided, refuse and say why; never substitute a default."

    No recorded result is affected: every frame in the digest corpus resolves inside the
    default budget, and all four recorded event pairs enumerate completely.
    """


def admissible_bond_orders(numbers, edges, index, limit=20000):
    """Every integer bond-order assignment consistent with neutral closed-shell valences.

    A set, not one Lewis structure. Which edge of benzene is "the double bond" depends on
    which Kekule structure was picked, so any property read off a single assignment would
    be an artefact of that choice; asking instead what holds across all of them is well
    defined. This is also the only formulation that is conformation-independent, which
    chemical identity has to be -- measured on the malonaldehyde enol, the same C=C ranges
    over 0.66 to 4.59 eV/rad^2 depending on whether the intramolecular hydrogen bond is
    closed, so neither a bond length nor a stiffness can carry this.

    Returns (solutions, info). solutions is None when the valences cannot be satisfied,
    an element falls outside the supported set, or the enumeration exceeds the limit. The
    caller must then record the stereochemistry as unresolved rather than guess at it.
    """
    active = [int(i) for i in index]
    if any(int(numbers[i]) not in VALENCE for i in active):
        outside = sorted(
            {
                chemical_symbols[int(numbers[i])]
                for i in active
                if int(numbers[i]) not in VALENCE
            }
        )
        return None, {"reason": "unsupported_elements", "elements": outside}
    incident = {i: [] for i in active}
    ordered = sorted(tuple(sorted(e)) for e in edges)
    for edge in ordered:
        for atom in edge:
            incident[atom].append(edge)
    remaining = {i: VALENCE[int(numbers[i])] - len(incident[i]) for i in active}
    if any(value < 0 for value in remaining.values()):
        return None, {"reason": "degree_exceeds_valence"}

    # Every edge starts at order one; what is left to place is the surplus valence.
    solutions, visited = [], 0

    def search(position, surplus, assignment):
        nonlocal visited
        visited += 1
        if visited > limit:
            raise RuntimeError("enumeration limit")
        if position == len(ordered):
            if all(value == 0 for value in surplus.values()):
                solutions.append(dict(assignment))
            return
        a, b = ordered[position]
        headroom = min(surplus[a], surplus[b], 2)
        for extra in range(headroom, -1, -1):
            surplus[a] -= extra
            surplus[b] -= extra
            assignment[(a, b)] = 1 + extra
            search(position + 1, surplus, assignment)
            surplus[a] += extra
            surplus[b] += extra
        assignment.pop((a, b), None)

    try:
        search(0, dict(remaining), {})
    except RuntimeError:
        return None, {"reason": "enumeration_limit", "limit": limit}
    if not solutions:
        return None, {"reason": "no_assignment_satisfies_valences"}
    return solutions, {"reason": None, "count": len(solutions)}


def locked_edges(numbers, edges, index, limit=20000):
    """Edges that are at least double in EVERY admissible assignment.

    Only those can carry E/Z: a bond that is double in one Kekule structure and single in
    another has no configuration to record, and a bond that is single in all of them cannot
    hold one. Returns (edges, info), with edges None when the assignment set is unresolved.
    """
    solutions, info = admissible_bond_orders(numbers, edges, index, limit)
    if solutions is None:
        return None, info
    always = frozenset(
        edge for edge in solutions[0] if all(solution[edge] >= 2 for solution in solutions)
    )
    return always, {**info, "locked": sorted(list(e) for e in always)}


def _locked_bond_parities(
    positions, numbers, edges, index, labels, locked, tolerance, group=None, canonical=None
):
    """E/Z parity across bonds that are double in every admissible bond-order assignment.

    Which bonds those are is decided by `locked_edges`, from the graph alone, because
    chemical identity has to be conformation-independent and neither of the two things
    tried before is. A bond length put a hard classifier inside an identity function and
    the malonaldehyde enol's C-OH sat 0.0002 A from it, so two structures differing by
    0.0003 A became two chemical nodes. Torsional stiffness moved that line rather than
    removing it: the same C=C measures 4.59 eV/rad^2 with the intramolecular hydrogen bond
    closed and 0.66 with it open, and those are conformers of one substance.

    An empty `locked` set therefore means "no bond can carry E/Z", and None is not passed
    here at all -- an unresolved valence is recorded in the key by the caller instead.

    Notes
    -----
    [1] The discriminant is the cosine between the two perpendicular components, not their
        dot product. The dot product carries the two substituent distances, so the old 1e-6
        cut was a length in Angstrom standing in for an angle: it fired on a short
        substituent that was nowhere near 90 degrees and never fired on a long one that was.
        At the crossing the cosine is zero and its sign is noise, so the band reports the
        configuration as absent instead of flipping with the last digit.
    """
    adjacency = {int(i): [] for i in index}
    for a, b in edges:
        adjacency[a].append(b)
        adjacency[b].append(a)
    parities = []
    for a, b in sorted(edges):
        if (a, b) not in locked:
            continue
        picked = []
        for near, far in ((a, b), (b, a)):
            options = [n for n in adjacency[near] if n != far]
            if not options:
                break
            best = max(labels[n] for n in options)
            tied = [n for n in options if labels[n] == best]
            if len(tied) > 1:
                # Same colour is a guess of equivalence; the certified question is
                # whether an automorphism actually swaps the tied substituents
                # (P1-3, same hole as the tetrahedral criterion). Without a
                # certified group the colour guess stands, as it always did.
                if group is None:
                    break  # substituents equivalent: no E/Z to record
                order = [int(i) for i in index]
                slot = {atom: k for k, atom in enumerate(order)}
                stab = _stabiliser_orbits(tied, group, slot, int(near))
                if len(stab) == 1:
                    break  # a swap exists: substituents equivalent, no E/Z
                # distinct under Stab(near): a real choice -- take the canonical
                # first rather than enumeration luck
                rank = canonical if canonical is not None else {n: n for n in index}
                picked.append(min(tied, key=lambda n: rank[n]))
                continue
            picked.append(tied[0])
        if len(picked) != 2:
            continue
        axis = positions[b] - positions[a]
        axis = axis / np.linalg.norm(axis)
        u = positions[picked[0]] - positions[a]
        v = positions[picked[1]] - positions[b]
        u = u - np.dot(u, axis) * axis
        v = v - np.dot(v, axis) * axis
        lengths = (float(np.linalg.norm(u)), float(np.linalg.norm(v)))
        if min(lengths) < 1e-6:
            continue
        # [1] the cosine between perpendicular components
        cosine = float(np.dot(u, v)) / (lengths[0] * lengths[1])
        parities.append(
            [
                tuple(sorted((labels[a], labels[b]))),
                int(np.sign(cosine)) if abs(cosine) > tolerance else "planar",
            ]
        )
    return sorted(
        [[list(pair), parity] for pair, parity in parities],
        key=lambda entry: (entry[0], str(entry[1])),
    )


# Below this the configuration at a centre is reported as "planar" rather than signed.
# Both discriminants are normalised to a dimensionless [-1, 1], so one number serves both:
# an ideal sp3 centre sits an order of magnitude above it and the one locked C=C in the
# frozen sample measures 0.9998, while a crossing is exactly zero.
PARITY_TOLERANCE = 0.01


def chemical_key(
    atoms,
    bond_scale=1.2,
    active=None,
    bond_order_limit=20000,
    charge_sensitive=False,
    charge=None,
    multiplicity=None,
    parity_tolerance=PARITY_TOLERANCE,
):
    """Identity of the chemical macrostate this structure belongs to.

    Returns the components as well as the digest so a record explains itself; two
    structures belong to the same macrostate exactly when their "key" agrees.
    """
    if not charge_sensitive and charge not in (None, 0):
        raise ValueError(
            "charge_sensitive is false, so a nonzero total charge cannot be "
            "represented; the potential does not respond to it"
        )
    index = resolve_active(atoms, active)
    graph = encode(atoms, bond_scale, active=active)
    numbers = atoms.numbers
    # One canonical_form call serves the colours (byte-identical to the old
    # canonical_labels: that degeneration is pinned in tests/test_canonical.py) and
    # the certified group the stereo criteria consume (P1-3, PLAN section 1.3). On
    # overflow the colours stand and the group is withheld -- the stereo criteria
    # then keep their colour rule, which is the behaviour they always had.
    form = canonical_form(numbers, graph.edges, index)
    labels = form.colours
    group = form.group if form.info.get("enumerated") else None
    canonical = {atom: k for k, atom in enumerate(form.order)} if group is not None else None
    locked, orders = locked_edges(numbers, graph.edges, index, bond_order_limit)
    if orders.get("reason") in BUDGET_REASONS:
        raise IdentityUnavailable(
            f"bond-order enumeration hit its budget ({orders['reason']}, "
            f"limit={bond_order_limit}); the key this would produce depends on the limit, "
            "not on the molecule. Raise bond_order_limit or exclude this structure."
        )
    components = {
        "graph_hash": _digest("|".join(sorted(labels.values())) + f"#{len(graph.edges)}"),
        "fragments": sorted(
            _formula(numbers, group) for group in _fragments(graph.edges, index)
        ),
        "tetrahedral_parity": _tetrahedral_parities(
            atoms.positions,
            numbers,
            graph.edges,
            index,
            labels,
            parity_tolerance,
            group=group,
            canonical=canonical,
        ),
        # None, not []. `locked` is None when the annotator could not decide which bonds
        # carry configuration, and passing an empty set there computed "no locked bonds"
        # -- which is the same value a molecule with genuinely no locked bonds produces.
        # The two are not the same statement and a reader cannot tell them apart from the
        # field. The key already distinguished them through `stereo_unresolved`, so the
        # information was not lost; the SHAPE of the field was lying, and the v2 digest
        # records that shape.
        #
        # Unknown is recorded as unknown. It is not "no stereochemical difference", and it
        # is not grounds for refusing the species either -- that separation is Registry.admit.
        "locked_bond_parity": (
            None
            if locked is None
            else _locked_bond_parities(
                atoms.positions,
                numbers,
                graph.edges,
                index,
                labels,
                locked,
                parity_tolerance,
                group=group,
                canonical=canonical,
            )
        ),
        # The STATE, not the reason. An unresolved substance must never be compared
        # against a resolved one on the quiet, so WHETHER the configuration could be
        # determined belongs in the key. WHY it could not is a diagnostic about the
        # resolver, and hashing a diagnostic makes it part of the substance's name:
        # improve the resolver's failure reporting and every affected structure silently
        # becomes a different species.
        #
        # `None` when resolved -- byte-identical to what this field hashed before -- so
        # the 2009 resolved frames in the corpus keep their keys, and every key quoted in
        # a frozen acceptance document still recomputes. Only the unresolved frames move,
        # and they are the ones whose keys carried the diagnostic. The reason itself is
        # recorded below, outside the hash.
        "stereo_unresolved": None if locked is not None else True,
        "charge_sensitive": bool(charge_sensitive),
    }
    if charge_sensitive:
        components["charge"] = charge
        components["multiplicity"] = multiplicity
    components["key"] = hashlib.sha256(
        json.dumps(components, sort_keys=True).encode()
    ).hexdigest()
    # Overwritten with the reason AFTER hashing: readers and stored records want the
    # reason, the key must not carry it. Diagnostics about the resolver, not about the
    # substance.
    components["stereo_unresolved"] = None if locked is not None else orders["reason"]
    components["configuration_protocol"] = _CONFIGURATION_PROTOCOL
    components["note"] = (
        "conformation deliberately excluded; only configurational stereochemistry contributes"
    )
    return components


def same_chemistry(a, b, bond_scale=1.2, active=None, **kwargs):
    return (
        chemical_key(a, bond_scale, active, **kwargs)["key"]
        == chemical_key(b, bond_scale, active, **kwargs)["key"]
    )


def automorphisms(atoms, bond_scale=1.2, active=None, limit=20000):
    """Edge-preserving permutations of equivalent atoms, as index arrays.

    Conformer identity is measured on geometry with fixed atom indices, so rotating a
    methyl group by 120 degrees moves every hydrogen to an equivalent site and looks
    like a new conformer even though nothing physical changed. Minimising RMSD over
    this group removes those duplicates, which is the same automorphism argument the
    chemical key already uses, applied one level down.

    Enumerated as the by-product of computing a canonical form (`canonical_form`,
    PLAN_2026-09-20.md section 1.1): refine the element colours to stability, then
    individualization-refinement -- individualize each member of the lexicographically
    first non-singleton colour class, refine, recurse. A discrete colouring is a leaf;
    the leaf with the minimal rendered edge set defines the canonical form, and two
    leaves with the same rendering are related by an automorphism, so the group falls
    out of the same walk that produces the form. The walk is exhaustive inside the
    budget and every choice is a fixed rule on colour strings, so the group is complete
    and reproducible: same graph in, same group out, whatever order the classes come in.

    The predecessor of THAT was point-wise backtracking over colour-class domains,
    which itself replaced taking the cartesian product of the permutations INSIDE each
    colour class and testing each complete candidate against the whole edge set. The
    product was factorial in the largest class and did not survive a tertiary carbon:
    tert-butyl chloride plus hydroxide has colour classes of 3 and 9, so 3! x 9! =
    2,177,280 candidates -- exactly computable, and exactly the wrong scaling -- for a
    group of order 1296. Measured: 19.8 s and a budget of 10,000,000 to finish, against
    20,000 by default, so b05's first probe attempt died at trial 1. The backtracking
    kernel then enumerated that same group in 3,889 search nodes / 41 ms, and those are
    the measurements the default budget stands on.

    `limit` bounds SEARCH NODES -- now the vertices of the individualization-refinement
    tree rather than assignment attempts -- and that is the budget's unit, reported in
    the returned info as `budget_unit`. It is deliberately not the old unit, which
    counted candidates in a product that no longer exists. The default 20,000 was kept
    rather than retuned: over the digest corpus (332 files, 2136 frames) the
    backtracking kernel's worst structure needed 57 nodes and b05's reactants 3,889, so
    the default cleared the hardest known case by a factor of five while still refusing
    something -- it is a budget, not a formality. The IR engine's own numbers are
    recorded against those in the plan's acceptance table, not re-asserted here.

    On overflow every partial result is discarded and only the identity is returned, with
    `reason = "candidate_limit"` -- the string `BUDGET_REASONS` keys on, so the event path
    still raises IdentityUnavailable rather than canonicalising against a group that was
    never certified. An incomplete group is never used.
    """
    index = resolve_active(atoms, active)
    graph = encode(atoms, bond_scale, active=active)
    form = canonical_form(atoms.numbers, graph.edges, index, limit=limit)
    return form.group, form.info


def _render_bonds(edges, mapping, numbers):
    """Bonds as element-tagged pairs under one relabelling, orientation-free."""
    rendered = []
    for a, b in edges:
        x, y = mapping[a], mapping[b]
        pair = sorted(((int(numbers[x]), x), (int(numbers[y]), y)))
        rendered.append(tuple(value for item in pair for value in item))
    return tuple(sorted(rendered))


def parity_map(components, field):
    """{locked bond (or centre) -> parity sign} from a node's key components."""
    out = {}
    for entry in components.get(field) or []:
        target, sign = entry
        out[tuple(sorted(target)) if isinstance(target, list) else target] = sign
    return out


def stereo_only_difference(first, second):
    """Do these two key-component sets differ ONLY in configurational stereochemistry?

    The single implementation of this test. It lives here, next to the classifier, because
    the acceptance checker needs the same question answered and having two copies is how the
    checker and the model come to disagree about what a class means.

    Two different things produce a key change with no bond change:

      real    E/Z isomerisation -- the locked-bond SET is identical and a parity sign is
              flipped. No bond changed because none had to; what changed is configurational
              stereochemistry, which is part of chemical identity by design.
      defect  the key changed for some other reason, e.g. conformation leaking into the key
              or a parity computed on a bond that is not actually locked.

    Returns (ok, reason).

    Notes
    -----
    [1] "key" is the digest of everything else, so of course it differs -- that the two keys
        differ IS the premise of the question being asked, and treating it as
        counter-evidence is self-refuting. It has to be ignored explicitly, because the two
        callers do not pass the same shape: the acceptance checker reads `key_components`
        from network.json, where publish() has already stripped "key", while the model
        passes `node.components`, where it is still present. Measured on P2 T=300 seed 71:
        the checker said "parity flipped, everything else identical" and the model said "key
        also differs" about the same pair. Sharing one implementation is not the same as
        sharing one input convention.
    """
    if first is None or second is None:
        return False, "key components not supplied, so the key change cannot be explained"
    if first.get("graph_hash") != second.get("graph_hash"):
        return False, "graph hashes differ, so this is not a stereochemistry-only change"
    if first.get("fragments") != second.get("fragments"):
        return False, "fragments differ"
    flipped = []
    for field in ("locked_bond_parity", "tetrahedral_parity"):
        a, b = parity_map(first, field), parity_map(second, field)
        if set(a) != set(b):
            return False, (
                f"{field} is defined on different targets: {sorted(a)} vs {sorted(b)}"
            )
        flipped += [target for target in a if a[target] != b[target]]
    if not flipped:
        return False, "no parity differs, so the key change is unexplained"
    # [1] the key differing is the premise, not a finding
    ignored = {"key", "locked_bond_parity", "tetrahedral_parity", "note", "automorphisms"}
    for field in set(first) | set(second):
        if field not in ignored and first.get(field) != second.get(field):
            return False, f"{field} also differs"
    return True, f"parity flipped on {flipped}, everything else identical"


def classify_transition(
    source_key, endpoint_key, broken, formed, source_components=None, endpoint_components=None
):
    """What happened between two minima, from the key and the bond delta together.

    Chemical-state identity and reaction-event identity are different questions. The key
    quotients away every redundancy of the state -- including the automorphism that makes
    a degenerate rearrangement end where it began -- and it must, or transferring one of
    three equivalent hydrogens would mint three products. But that same quotient cannot be
    what decides whether a reaction occurred, because it is blind to the path: a proton
    that moves from one oxygen to the other returns a structure with the identical key and
    a bond set that is not the one it started with.

    So both are needed. A vanishing bond delta is a conformational change however far the
    geometry moved; a non-vanishing one is a reaction whether or not the key changed, and
    when the key does not change the reaction is degenerate -- an automerization.

    The fourth cell -- key changed, no bond changed -- was originally named
    `key_change_without_bond_change` on the assumption that it is always a defect, because
    it is impossible if the key is a function of the bond graph alone. But the key is
    deliberately NOT that: it also carries configurational stereochemistry. So E/Z
    isomerisation lands in that cell legitimately, and it is a real event, just a
    higher-energy one. Measured on 3-oxobutanal, twice independently: the same locked bond,
    parity flipped from -1 to +1, graph hash unchanged, 365-404 meV above the reactant.

    Given both key-component sets the fourth cell is therefore split: a parity flip on an
    otherwise identical component set is `configurational_isomerisation`; anything else in
    that cell keeps the old name and remains a defect to be diagnosed. Without the
    components it cannot be told apart, so the conservative name is kept.
    """
    changed = bool(broken or formed)
    if source_key == endpoint_key:
        return "conformational_transition" if not changed else "degenerate_reaction"
    if changed:
        return "reaction"
    stereo, _ = stereo_only_difference(source_components, endpoint_components)
    return "configurational_isomerisation" if stereo else "key_change_without_bond_change"


def _generated_group(index, generators, limit):
    """The group generated by permutations of `index`, not their union.

    A union of two subgroups is not a subgroup -- composition leaves it -- so taking a
    minimum over the union is not a canonical form under either group, let alone under
    both. Measured on the smallest case that separates them: Aut(K1,3) has 6 elements,
    Aut(P4) has 2, their union has 7 and the group they generate has 24, and relabelling
    an event by an element of Aut(P4) moved the union's minimum while leaving the group's
    fixed. tests/test_reaction_events.py pins that pair.

    The closure is bounded by the same `limit` the enumeration uses, and overflowing it
    raises rather than falling back, because a partial closure is exactly the union
    problem again with a larger union.
    """
    order = [int(a) for a in index]
    slot = {atom: i for i, atom in enumerate(order)}
    group, frontier = {tuple(order)}, [tuple(order)]
    while frontier:
        current = frontier.pop()
        for generator in generators:
            composed = tuple(generator[slot[atom]] for atom in current)
            if composed in group:
                continue
            if len(group) >= limit:
                raise IdentityUnavailable(
                    f"the group generated by the two endpoints' automorphisms exceeds "
                    f"{limit} elements, so the event key would depend on where the "
                    f"closure stopped rather than on the reaction. Raise "
                    f"automorphism_limit or exclude this pair."
                )
            group.add(composed)
            frontier.append(composed)
    return sorted(group)


def _superposition_form(source, endpoint, bond_scale, active, limit):
    """The event as ONE edge-coloured graph, canonically labelled (PLAN section 1.2).

    `key` below is an identity within one atom numbering: its render carries raw
    indices and the group can only move an atom inside its own orbit, so two builds
    of one system mint two keys for one reaction (test_quotient_invariance pinned
    that as xfail for exactly as long as the fix was an open design decision). The
    structural identity cannot be two separate canonical forms -- source and endpoint
    orderings have nothing to do with each other -- so it is the canonical form of
    the event ITSELF: one graph over the union of the endpoint edge sets, each edge
    coloured kept / broken / formed. Numbering-free by construction, and the kept
    edges ride inside the certificate, which is what separates same-pattern
    different-substance events without the endpoint-hash context tag the old key
    needs. Direction is quotiented the same way `key` quotients it: compute the form
    with broken and formed swapped and keep the smaller certificate.
    """
    numbers = source.numbers
    ga = encode(source, bond_scale, active=active)
    gb = encode(endpoint, bond_scale, active=active)
    index = resolve_active(source, active)
    broken, formed = ga.edges - gb.edges, gb.edges - ga.edges
    union = sorted(ga.edges | gb.edges)

    def one_way(broken_set, formed_set):
        colours = {
            edge: "broken" if edge in broken_set else "formed" if edge in formed_set else "kept"
            for edge in union
        }
        form = canonical_form(numbers, union, index, edge_colours=colours, limit=limit)
        if not form.info.get("enumerated"):
            raise IdentityUnavailable(
                "the superposition graph's canonical form did not certify inside its "
                "budget, so no structural identity exists at this limit; raising "
                "automorphism_limit or excluding the pair beats a structural key that "
                "silently depends on the numbering."
            )
        position = {atom: k for k, atom in enumerate(form.order)}

        def render(edge_set):
            rendered = []
            for a, b in edge_set:
                x, y = position[int(a)], position[int(b)]
                pair = sorted(((int(numbers[int(a)]), x), (int(numbers[int(b)]), y)))
                rendered.append(tuple(value for item in pair for value in item))
            return tuple(sorted(rendered))

        return form, render(broken_set), render(formed_set)

    form, broken_rendered, formed_rendered = min(
        one_way(broken, formed),
        one_way(formed, broken),
        key=lambda entry: entry[0].certificate,
    )
    structural_key = _digest(repr((form.certificate, broken_rendered, formed_rendered)))
    return structural_key, {
        "broken": [list(edge) for edge in broken_rendered],
        "formed": [list(edge) for edge in formed_rendered],
    }


def reaction_event_key(source, endpoint, bond_scale=1.2, active=None, limit=20000):
    """Identity of a reaction event, quotiented by symmetry and by direction.

    Storing raw atom indices would let equivalent atoms manufacture duplicate channels --
    transferring each of three equivalent hydrogens would look like three reactions -- so
    the broken and formed sets are canonicalized under the group GENERATED by the
    automorphism groups of the two endpoints, which is the same argument the chemical key
    already makes one level up. Generated, not unioned: see `_generated_group`.

    Direction is quotiented too: the forward and reverse observations of one channel are
    two observations, not two channels, which matches the existing treatment of a saddle's
    two endpoints as undirected structural evidence rather than as a pair of directed edges.

    If either automorphism group exceeds the enumeration limit only the identity is used,
    so the key over-counts channels rather than silently merging distinct ones -- the same
    failure direction the rest of the symmetry handling takes.
    """
    numbers = source.numbers
    ga = encode(source, bond_scale, active=active)
    gb = encode(endpoint, bond_scale, active=active)
    broken, formed = ga.edges - gb.edges, gb.edges - ga.edges
    index = resolve_active(source, active)

    generators, enumerated = [], True
    for structure in (source, endpoint):
        found, info = automorphisms(structure, bond_scale, active, limit)
        enumerated = enumerated and info.get("enumerated", False)
        generators.extend(tuple(int(b) for b in permutation) for permutation in found)

    if not enumerated:
        raise IdentityUnavailable(
            "the automorphism group was not enumerated inside its budget, so the bond "
            "delta is canonicalised against the identity permutation alone and the event "
            "key depends on the limit rather than on the reaction. Raise "
            "automorphism_limit or exclude this pair."
        )

    relabellings = [
        dict(zip((int(a) for a in index), element))
        for element in _generated_group(index, generators, limit)
    ]

    def canonical(first, second):
        return min(
            (_render_bonds(first, mapping, numbers), _render_bonds(second, mapping, numbers))
            for mapping in relabellings
        )

    form = min(canonical(broken, formed), canonical(formed, broken))

    # The bond pattern alone is not a global identity: two different substances can break
    # and form the same elements at the same indices, and did in the malonaldehyde and
    # 3-oxobutanal preflights. Tagging the digest with the unordered pair of endpoint graph
    # hashes separates them without giving the key a direction.
    def graph_hash(structure):
        graph = encode(structure, bond_scale, active=active)
        labels = canonical_labels(
            structure.numbers, graph.edges, resolve_active(structure, active)
        )
        return _digest("|".join(sorted(labels.values())) + f"#{len(graph.edges)}")

    context = tuple(sorted((graph_hash(source), graph_hash(endpoint))))
    form_with_context = (form, context)
    digest = hashlib.sha256(repr(form_with_context).encode()).hexdigest()[:16]
    # Decision 1 (2026-09-20): ADDED fields, `key` untouched. Within one run all
    # structures share a numbering so `key` keeps doing its job -- b04's frozen
    # criteria quote it and every recorded digest stands; structural_key is the one
    # valid across runs and builds.
    structural_key, structural_form = _superposition_form(
        source, endpoint, bond_scale, active, limit
    )
    return {
        "key": digest,
        "structural_key": structural_key,
        "structural_form": structural_form,
        "canonical": form,
        "endpoint_graphs": list(context),
        "broken": [list(e) for e in sorted(broken)],
        "formed": [list(e) for e in sorted(formed)],
        "symmetry_enumerated": enumerated,
        "relabellings": len(relabellings),
        "meaning": _REACTION_EVENT_KEY_MEANING,
    }


def free_aligned_symmetric_rmsd(
    a, b, permutations_, active=None, free_bonds=(), bond_scale=1.2, samples=24
):
    """symmetric_rmsd, additionally minimized over rotations about coordinates that carry
    no energy.

    A torsion whose stiffness has fallen to zero connects the structures on either side of
    it by a path with no barrier, so they are one basin and one microstate however far
    apart their coordinates are. Plain RMSD says otherwise, and a genuinely free rotor
    therefore mints an unbounded number of spurious conformers. Quotienting the comparison
    by those coordinates is the same move the chemical key, the symmetry-aware RMSD and the
    rotor fundamental domain already make, applied to the one redundancy that is energetic
    rather than combinatorial. In Morse-Bott terms it is the neutral subspace: the
    transition-state criterion asks for exactly one unstable direction and says nothing
    about how many flat ones there are, so flat ones must not be allowed to multiply states.

    Which coordinates are free has to be measured, and only on the structure where it was
    measured is the answer known -- so `free_bonds` is supplied by the caller rather than
    guessed here. Passing a stiff or merely soft coordinate would wrongly merge two real
    conformers, which is why nothing infers this from the graph alone.

    Costs no force evaluations: rotation about a bridge bond is exact geometry.
    """
    from .perturbations import step_torsion, torsion_on_bond
    from .state import encode

    best = symmetric_rmsd(a, b, permutations_, active)
    if not free_bonds:
        return best
    graph = encode(b, bond_scale, active=active)
    labels = canonical_labels(b.numbers, graph.edges, graph.index)
    torsions = [
        t
        for t in (torsion_on_bond(graph, labels, bond) for bond in free_bonds)
        if t is not None
    ]
    if not torsions:
        return best
    current = b
    grid = np.linspace(0.0, 2 * np.pi, samples, endpoint=False)[1:]
    for _ in range(2):
        improved = False
        for torsion in torsions:
            for delta in grid:
                rotated, _ = step_torsion(current, torsion, float(delta), in_place=False)
                distance = symmetric_rmsd(a, rotated, permutations_, active)
                if distance < best - 1e-12:
                    best, current, improved = distance, rotated, True
        if not improved:
            break
    return best


def symmetric_rmsd(a, b, permutations_, active=None):
    """Smallest Kabsch RMSD over a set of index permutations of b."""
    from .state import aligned_rmsd

    index = resolve_active(a, active)
    best = float("inf")
    for permutation in permutations_:
        relabelled = b.copy()
        positions = relabelled.positions.copy()
        positions[index] = b.positions[permutation]
        relabelled.set_positions(positions)
        best = min(best, aligned_rmsd(a, relabelled, active))
    return best
